#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

console.log('🎭 3D MC Presenter PRO - Environment Setup');
console.log('==========================================\n');

async function setupEnvironment() {
  try {
    // Check if .env already exists
    const envPath = path.join(__dirname, '.env');
    if (fs.existsSync(envPath)) {
      const overwrite = await question('⚠️  .env file already exists. Overwrite? (y/n): ');
      if (overwrite.toLowerCase() !== 'y') {
        console.log('❌ Setup cancelled.');
        rl.close();
        return;
      }
    }

    console.log('📝 Please provide your API keys:\n');

    // Get AI provider choice
    const aiProvider = await question('Choose AI provider (gemini/openai/claude) [gemini]: ') || 'gemini';
    
    let geminiKey = '';
    let openaiKey = '';
    let claudeKey = '';

    if (aiProvider === 'gemini') {
      geminiKey = await question('🔑 Gemini API Key (get from https://aistudio.google.com/): ');
    } else if (aiProvider === 'openai') {
      openaiKey = await question('🔑 OpenAI API Key (get from https://platform.openai.com/): ');
    } else if (aiProvider === 'claude') {
      claudeKey = await question('🔑 Claude API Key (get from https://console.anthropic.com/): ');
    }

    const ttsKey = await question('🔑 Google TTS API Key (get from https://console.cloud.google.com/): ');

    // Generate .env content
    const envContent = `# ==========================================
# 3D MC Presenter PRO - Environment Configuration
# Auto-generated by setup-env.js
# ==========================================

# AI PROVIDER SELECTION
AI_PROVIDER=${aiProvider}

# ==========================================
# GOOGLE GEMINI API CONFIGURATION
# ==========================================
GEMINI_API_KEY=${geminiKey}
GEMINI_MODEL=gemini-pro
GEMINI_TEMPERATURE=0.7
GEMINI_MAX_TOKENS=1000

# ==========================================
# OPENAI GPT API CONFIGURATION  
# ==========================================
OPENAI_API_KEY=${openaiKey}
OPENAI_MODEL=gpt-3.5-turbo
OPENAI_TEMPERATURE=0.7
OPENAI_MAX_TOKENS=1000

# ==========================================
# ANTHROPIC CLAUDE API CONFIGURATION
# ==========================================
CLAUDE_API_KEY=${claudeKey}
CLAUDE_MODEL=claude-3-sonnet-20240229
CLAUDE_TEMPERATURE=0.7
CLAUDE_MAX_TOKENS=1000

# ==========================================
# GOOGLE TEXT-TO-SPEECH API
# ==========================================
TTS_API_KEY=${ttsKey}
TTS_LANGUAGE_CODE=vi-VN
TTS_VOICE_NAME=vi-VN-Wavenet-A
TTS_ENCODING=MP3

# Voice mapping for different characters
TTS_VOICE_FEMALE1=vi-VN-Wavenet-A
TTS_VOICE_FEMALE2=vi-VN-Wavenet-B
TTS_VOICE_FEMALE3=vi-VN-Wavenet-C
TTS_VOICE_FEMALE4=vi-VN-Wavenet-D
TTS_VOICE_FEMALE5=vi-VN-Wavenet-E
TTS_VOICE_FEMALE6=vi-VN-Wavenet-F

# ==========================================
# SERVER CONFIGURATION
# ==========================================
PORT=3001
NODE_ENV=development
HOST=localhost

# CORS Configuration
CORS_ORIGIN=http://localhost:3000
CORS_CREDENTIALS=true

# ==========================================
# DEFAULT SETTINGS
# ==========================================
DEFAULT_CHARACTER=female1
DEFAULT_OUTFIT=casual
DEFAULT_HAIR=long
DEFAULT_ACCESSORY=none
DEFAULT_COLOR=#ff6b6b

# Enable features
ENABLE_AI_RESPONSES=true
ENABLE_TTS=true
ENABLE_LIP_SYNC=true
ENABLE_CHARACTER_SWITCHING=true
ENABLE_OUTFIT_CUSTOMIZATION=true
ENABLE_CAMERA_CONTROLS=true

# OBS Stream settings
OBS_WIDTH=1920
OBS_HEIGHT=1080
OBS_FPS=30

# Debug settings
DEBUG=false
DEBUG_THREEJS=false
DEBUG_AI=false
DEBUG_TTS=false
`;

    // Write .env file
    fs.writeFileSync(envPath, envContent);
    
    console.log('\n✅ .env file created successfully!');
    console.log('\n📋 Next steps:');
    console.log('1. npm install');
    console.log('2. npm run dev:full');
    console.log('3. Open http://localhost:3000');
    console.log('\n📚 For more options, see .env.full');
    
  } catch (error) {
    console.error('❌ Error during setup:', error.message);
  }
  
  rl.close();
}

function question(query) {
  return new Promise(resolve => rl.question(query, resolve));
}

// Run setup
setupEnvironment();
